a=float(input("Enter 1st num:"))
b=float(input("Enter 2nd num:"))
print("Sum:",a+b)
print("Diff:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("Floor Division:",a//b)
print("Remainder:",a%b)
print("Exponential:",a**b)